# Generated by Django 5.0.4 on 2024-04-30 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('married', models.CharField(max_length=10)),
                ('dependents', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('self_employed', models.CharField(max_length=10)),
                ('applicant_income', models.FloatField()),
                ('coapplicant_income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_amount_term', models.IntegerField()),
                ('credit_history', models.CharField(max_length=10)),
                ('property_area', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
