# Generated by Django 5.0.4 on 2024-04-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loan_approval',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
